# 80포트: Let's Encrypt 인증(webroot) + 나머지는 https로 이동
server {
    listen 80;
    server_name cyberfondo.yangarch.net;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
