[program:rocyg_crawler]
command=/절대경로/.venv/bin/python main.py
directory=/절대경로/
autostart=true
autorestart=true
startretries=5
stderr_logfile=/var/log/rocyg_crawler.err.log
stdout_logfile=/var/log/rocyg_crawler.out.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile_backups=3
environment=PYTHONUNBUFFERED="1"
